const API='https://graph.threads.net/v1.0';
const OAUTH='https://graph.threads.net';
const COOKIE='t1k_session';

export default {
  async fetch(req,env){
    try{
      const u=new URL(req.url), p=u.pathname;
      if(p==='/api/session'&&req.method==='POST') return login(req,env);
      if(p==='/auth/threads/callback') return callback(req,env);
      if(p.startsWith('/api/')){
        if(!(await authed(req,env))) return J({error:'unauthorized'},401);
        if(p==='/api/dashboard') return dashboard(env);
        if(p==='/api/auth/threads/start') return startOAuth(req,env);
        if(p==='/api/auth/disconnect'&&req.method==='POST'){await env.DB.prepare('DELETE FROM accounts').run();return J({ok:true});}
        if(p==='/api/sync'&&req.method==='POST') return J(await sync(env));
        if(p==='/api/config'&&req.method==='POST') return saveConfig(req,env);
        if(p==='/api/journal'&&req.method==='POST') return saveJournal(req,env);
        return J({error:'not_found'},404);
      }
      return env.ASSETS.fetch(req);
    }catch(e){console.error(e);return J({error:'server_error',detail:String(e?.message||e)},500);}
  },
  async scheduled(_,env,ctx){ctx.waitUntil(sync(env));}
};

async function login(req,env){const b=await body(req);if(!env.DASHBOARD_SECRET||b.passcode!==env.DASHBOARD_SECRET)return J({error:'invalid_login'},401);const s=await hash(env.DASHBOARD_SECRET);return J({ok:true},200,{'Set-Cookie':`${COOKIE}=${s}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`});}
async function authed(req,env){const c=cookies(req.headers.get('Cookie')||'');return !!env.DASHBOARD_SECRET&&c[COOKIE]===await hash(env.DASHBOARD_SECRET);}
async function startOAuth(req,env){if(!env.THREADS_APP_ID)return J({error:'THREADS_APP_ID_not_set'},500);const origin=new URL(req.url).origin,redirect=`${origin}/auth/threads/callback`,state=crypto.randomUUID();await env.DB.prepare('INSERT OR REPLACE INTO oauth_states(state,expires_at) VALUES(?,?)').bind(state,Date.now()+600000).run();const a=new URL('https://threads.net/oauth/authorize');a.searchParams.set('client_id',env.THREADS_APP_ID);a.searchParams.set('redirect_uri',redirect);a.searchParams.set('scope','threads_basic,threads_manage_insights');a.searchParams.set('response_type','code');a.searchParams.set('state',state);return J({url:a.toString(),redirect_uri:redirect});}
async function callback(req,env){const u=new URL(req.url),code=u.searchParams.get('code'),state=u.searchParams.get('state');if(!code||!state)return page('OAuth gagal','Code/state tidak ditemukan.',false);const r=await env.DB.prepare('SELECT expires_at FROM oauth_states WHERE state=?').bind(state).first();if(!r||Number(r.expires_at)<Date.now())return page('OAuth gagal','State tidak valid atau kedaluwarsa.',false);await env.DB.prepare('DELETE FROM oauth_states WHERE state=?').bind(state).run();if(!env.THREADS_APP_SECRET)return page('Konfigurasi belum lengkap','THREADS_APP_SECRET belum diset.',false);
 const redirect=`${u.origin}/auth/threads/callback`,f=new FormData();f.set('client_id',env.THREADS_APP_ID);f.set('client_secret',env.THREADS_APP_SECRET);f.set('grant_type','authorization_code');f.set('redirect_uri',redirect);f.set('code',code);
 const sr=await fetch(`${OAUTH}/oauth/access_token`,{method:'POST',body:f}),sd=await sr.json();if(!sr.ok||!sd.access_token)return page('Token gagal',esc(JSON.stringify(sd)),false);
 const lu=new URL(`${OAUTH}/access_token`);lu.searchParams.set('grant_type','th_exchange_token');lu.searchParams.set('client_secret',env.THREADS_APP_SECRET);const lr=await fetch(lu,{headers:{Authorization:`Bearer ${sd.access_token}`}}),ld=await lr.json();const token=ld.access_token||sd.access_token,exp=Date.now()+Number(ld.expires_in||86400)*1000;
 const pr=await TF('/me?fields=id,username',token);if(!pr.ok)return page('Profil gagal dibaca',esc(JSON.stringify(pr.data)),false);const e=await encrypt(token,env.TOKEN_ENCRYPTION_KEY),now=new Date().toISOString();await env.DB.prepare(`INSERT INTO accounts(threads_user_id,username,token_ciphertext,token_iv,token_expires_at,connected_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(threads_user_id) DO UPDATE SET username=excluded.username,token_ciphertext=excluded.token_ciphertext,token_iv=excluded.token_iv,token_expires_at=excluded.token_expires_at,updated_at=excluded.updated_at`).bind(String(pr.data.id),pr.data.username||'',e.ciphertext,e.iv,exp,now,now).run();await sync(env);return page('Threads berhasil terhubung',`@${esc(pr.data.username||'')} sudah terhubung.`,true);}

async function sync(env){const a=await env.DB.prepare('SELECT * FROM accounts ORDER BY id DESC LIMIT 1').first();if(!a)return {ok:true,connected:false};const token=await decrypt(a.token_ciphertext,a.token_iv,env.TOKEN_ENCRYPTION_KEY),until=Math.floor(Date.now()/1000),since=until-86400;
 const fr=await TF('/me/threads_insights?metric=followers_count',token);if(!fr.ok)throw new Error('followers insight: '+JSON.stringify(fr.data));const ar=await TF(`/me/threads_insights?metric=views,likes,replies,reposts,quotes&since=${since}&until=${until}`,token);if(!ar.ok)throw new Error('account insight: '+JSON.stringify(ar.data));const m={...metrics(ar.data?.data),...metrics(fr.data?.data)},now=new Date().toISOString();await env.DB.prepare('INSERT INTO snapshots(threads_user_id,captured_at,followers_count,views,likes,replies,reposts,quotes) VALUES(?,?,?,?,?,?,?,?)').bind(a.threads_user_id,now,m.followers_count||0,m.views||0,m.likes||0,m.replies||0,m.reposts||0,m.quotes||0).run();
 const ps=await TF('/me/threads?fields=id,media_type,permalink,username,text,timestamp&limit=30',token);let n=0;if(ps.ok&&Array.isArray(ps.data?.data))for(const p of ps.data.data){const ir=await TF(`/${p.id}/insights?metric=views,likes,replies,reposts,quotes,shares`,token),x=ir.ok?metrics(ir.data?.data):{};await env.DB.prepare(`INSERT INTO posts(thread_id,threads_user_id,username,text,permalink,media_type,published_at,views,likes,replies,reposts,quotes,shares,synced_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(thread_id) DO UPDATE SET text=excluded.text,permalink=excluded.permalink,media_type=excluded.media_type,published_at=excluded.published_at,views=excluded.views,likes=excluded.likes,replies=excluded.replies,reposts=excluded.reposts,quotes=excluded.quotes,shares=excluded.shares,synced_at=excluded.synced_at`).bind(String(p.id),a.threads_user_id,p.username||a.username||'',p.text||'',p.permalink||'',p.media_type||'',p.timestamp||'',x.views||0,x.likes||0,x.replies||0,x.reposts||0,x.quotes||0,x.shares||0,now).run();n++;}await env.DB.prepare('UPDATE accounts SET updated_at=? WHERE threads_user_id=?').bind(now,a.threads_user_id).run();return {ok:true,connected:true,post_count:n,synced_at:now};}

async function dashboard(env){const account=await env.DB.prepare('SELECT threads_user_id,username,connected_at,updated_at FROM accounts ORDER BY id DESC LIMIT 1').first(),config=await env.DB.prepare('SELECT * FROM experiment_config WHERE id=1').first();let snapshots=[],posts=[];if(account){snapshots=(await env.DB.prepare('SELECT captured_at,followers_count,views,likes,replies,reposts,quotes FROM snapshots WHERE threads_user_id=? ORDER BY captured_at DESC LIMIT 120').bind(account.threads_user_id).all()).results||[];posts=(await env.DB.prepare('SELECT thread_id,text,permalink,media_type,published_at,views,likes,replies,reposts,quotes,shares FROM posts WHERE threads_user_id=? ORDER BY published_at DESC LIMIT 30').bind(account.threads_user_id).all()).results||[];}return J({connected:!!account,account,config,snapshots,posts});}
async function saveConfig(req,env){const b=await body(req),now=new Date().toISOString();await env.DB.prepare(`INSERT INTO experiment_config(id,start_date,baseline_followers,target_followers,duration_days,updated_at) VALUES(1,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET start_date=excluded.start_date,baseline_followers=excluded.baseline_followers,target_followers=excluded.target_followers,duration_days=excluded.duration_days,updated_at=excluded.updated_at`).bind(b.start_date||new Date().toISOString().slice(0,10),Number(b.baseline_followers||0),Number(b.target_followers||1000),Number(b.duration_days||30),now).run();return J({ok:true});}
async function saveJournal(req,env){const b=await body(req),d=b.journal_date||new Date().toISOString().slice(0,10),now=new Date().toISOString();await env.DB.prepare(`INSERT INTO journal(journal_date,hypothesis,worked,failed,next_test,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(journal_date) DO UPDATE SET hypothesis=excluded.hypothesis,worked=excluded.worked,failed=excluded.failed,next_test=excluded.next_test,updated_at=excluded.updated_at`).bind(d,b.hypothesis||'',b.worked||'',b.failed||'',b.next_test||'',now).run();return J({ok:true});}

async function TF(path,token){const r=await fetch(API+path,{headers:{Authorization:`Bearer ${token}`}});let d={};try{d=await r.json()}catch{}return {ok:r.ok,status:r.status,data:d};}
function metrics(a=[]){const o={};for(const i of a){let v=0;if(i?.total_value?.value!==undefined)v=Number(i.total_value.value)||0;else if(Array.isArray(i?.values)&&i.values.length)v=Number(i.values.at(-1)?.value)||0;o[i.name]=v;}return o;}
async function encrypt(t,k){if(!k||!/^[0-9a-fA-F]{64}$/.test(k))throw new Error('TOKEN_ENCRYPTION_KEY harus 64 hex karakter');const key=await crypto.subtle.importKey('raw',hex(k),{name:'AES-GCM'},false,['encrypt']),iv=crypto.getRandomValues(new Uint8Array(12)),c=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(t));return {ciphertext:b64(new Uint8Array(c)),iv:b64(iv)}}
async function decrypt(c,i,k){const key=await crypto.subtle.importKey('raw',hex(k),{name:'AES-GCM'},false,['decrypt']),p=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(i)},key,unb64(c));return new TextDecoder().decode(p)}
function hex(h){const a=new Uint8Array(h.length/2);for(let i=0;i<a.length;i++)a[i]=parseInt(h.slice(i*2,i*2+2),16);return a}function b64(a){let s='';for(const x of a)s+=String.fromCharCode(x);return btoa(s)}function unb64(s){const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
async function hash(s){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return b64(new Uint8Array(d)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function cookies(s){const o={};for(const p of s.split(';')){const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=p.slice(i+1).trim()}return o}async function body(r){try{return await r.json()}catch{return {}}}function J(d,s=200,h={}){return new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...h}})}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function page(t,m,ok){return new Response(`<!doctype html><meta charset=utf-8><style>body{font-family:system-ui;background:#07111f;color:#fff;display:grid;place-items:center;min-height:100vh}.c{max-width:520px;background:#10243a;padding:28px;border-radius:20px;text-align:center}p{color:#adc1d4}</style><div class=c><h1>${t}</h1><p>${m}</p></div>${ok?'<script>setTimeout(()=>location.href="/",1200)</script>':''}`,{headers:{'Content-Type':'text/html; charset=utf-8'}})}
